# Generated by Django 2.1.5 on 2022-06-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220627_0644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='passward',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.IntegerField(default=11),
        ),
    ]
