# Generated by Django 4.0.5 on 2022-06-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_filemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comment',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='star',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumb_up',
            field=models.BigIntegerField(default=0),
        ),
    ]
