# Generated by Django 4.0.5 on 2022-06-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220627_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('phone', models.IntegerField(default=11)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
